# (1) import libraries

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

# (2) preparing iris dataset

In [2]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(90, 4)
(90,)
(60, 4)
(60,)


# (3) parameters estimation

In [3]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)
print(mu_0)
print(sigma_0)

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print(mu_1)
print(sigma_1)

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print(mu_2)
print(sigma_2)

[4.99259259 3.42592593 1.44814815 0.22592593]
[[ 0.11301994  0.09250712  0.00037037  0.01096866]
 [ 0.09250712  0.11737892 -0.00245014  0.00968661]
 [ 0.00037037 -0.00245014  0.01490028  0.00062678]
 [ 0.01096866  0.00968661  0.00062678  0.00660969]]
[5.9        2.74857143 4.23428571 1.32285714]
[[0.25823529 0.08264706 0.16323529 0.05029412]
 [0.08264706 0.09315966 0.0829916  0.04268067]
 [0.16323529 0.0829916  0.22173109 0.07801681]
 [0.05029412 0.04268067 0.07801681 0.04063866]]
[6.66785714 2.95       5.58571429 2.01785714]
[[0.52003968 0.09092593 0.38582011 0.0635582 ]
 [0.09092593 0.10333333 0.04333333 0.04018519]
 [0.38582011 0.04333333 0.35460317 0.04804233]
 [0.0635582  0.04018519 0.04804233 0.06596561]]


# (4) bayesian decision making

In [4]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9500
