# (1) import libraries

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

# (2) preparing iris dataset

In [2]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(90, 4)
(90,)
(60, 4)
(60,)


# (3) parameters estimation

In [3]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)
print(mu_0)
print(sigma_0)

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print(mu_1)
print(sigma_1)

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print(mu_2)
print(sigma_2)

[4.99677419 3.41290323 1.46451613 0.25483871]
[[0.09232258 0.08304301 0.01321505 0.00584946]
 [0.08304301 0.14982796 0.01413978 0.00760215]
 [0.01321505 0.01413978 0.02303226 0.00667742]
 [0.00584946 0.00760215 0.00667742 0.01322581]]
[5.91212121 2.71212121 4.21818182 1.3030303 ]
[[0.25484848 0.07578598 0.18758523 0.05402462]
 [0.07578598 0.09922348 0.08039773 0.03996212]
 [0.18758523 0.08039773 0.23653409 0.07525568]
 [0.05402462 0.03996212 0.07525568 0.04217803]]
[6.63076923 2.95384615 5.64230769 2.08076923]
[[0.48861538 0.09827692 0.38064615 0.03901538]
 [0.09827692 0.10658462 0.07963077 0.04987692]
 [0.38064615 0.07963077 0.36493846 0.04324615]
 [0.03901538 0.04987692 0.04324615 0.06321538]]


# (4) bayesian decision making

In [4]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9500
