# (1) import libraries

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

# (2) preparing iris dataset

In [2]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(90, 4)
(90,)
(60, 4)
(60,)


# (3) parameters estimation

In [3]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)
print(mu_0)
print(sigma_0)

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print(mu_1)
print(sigma_1)

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print(mu_2)
print(sigma_2)

[5.03142857 3.5        1.46285714 0.23428571]
[[0.11810084 0.08794118 0.02384874 0.01242017]
 [0.08794118 0.12647059 0.01411765 0.01441176]
 [0.02384874 0.01411765 0.02710924 0.00572269]
 [0.01242017 0.01441176 0.00572269 0.00878992]]
[5.84285714 2.73571429 4.22142857 1.31071429]
[[0.31661376 0.10952381 0.24275132 0.07100529]
 [0.10952381 0.11275132 0.11661376 0.04886243]
 [0.24275132 0.11661376 0.30100529 0.09679894]
 [0.07100529 0.04886243 0.09679894 0.04543651]]
[6.46666667 2.93703704 5.42592593 2.05185185]
[[0.39846154 0.11512821 0.28974359 0.06102564]
 [0.11512821 0.11011396 0.08746439 0.05185185]
 [0.28974359 0.08746439 0.28430199 0.05091168]
 [0.06102564 0.05185185 0.05091168 0.05797721]]


# (4) bayesian decision making

In [4]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9333
