In [10]:
import tensorflow as tf
import pandas as pd


In [11]:
# Đọc tệp Excel bằng pandas
file_path = "/kaggle/input/btxrd-v3/classification.xlsx"  # Đường dẫn đến file Excel

In [12]:
df = pd.read_excel(file_path)

# Xử lý giá trị NaN bằng cách điền 0 (hoặc giá trị khác phù hợp)
df = df.fillna(0)

# Chuyển đổi toàn bộ cột kiểu object (chuỗi) thành string để tránh lỗi
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype(str)

# Chuyển DataFrame thành dataset
dataset = tf.data.Dataset.from_tensor_slices(dict(df))

# Kiểm tra dataset
for data in dataset.take(1):
    print(data)

{'image_id': <tf.Tensor: shape=(), dtype=string, numpy=b'IMG000001.jpeg'>, 'center': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=48>, 'gender': <tf.Tensor: shape=(), dtype=string, numpy=b'F'>, 'neoplasm': <tf.Tensor: shape=(), dtype=string, numpy=b'malignant'>, 'tumor_type': <tf.Tensor: shape=(), dtype=string, numpy=b'other mt'>, 'img_type': <tf.Tensor: shape=(), dtype=string, numpy=b'frontal'>, 'skeletal_type': <tf.Tensor: shape=(), dtype=string, numpy=b'pelvis'>, 'bones_type': <tf.Tensor: shape=(), dtype=string, numpy=b'hip bone'>, 'points': <tf.Tensor: shape=(), dtype=string, numpy=b'[[[2027.9285714285713, 1219.9285714285713], [2013.642857142857, 1184.2142857142858], [2020.7857142857144, 1121.7142857142858], [2088.642857142857, 1027.0714285714287], [2138.642857142857, 957.4285714285714], [2172.5714285714284, 875.2857142857143], [2174.3571428571427, 827.0714285714287], [2133.285714285714, 802.0714285714287], [2081.5, 732.4285714285714]